"""Add food budget fields to user table

Revision ID: 001
Revises: 
Create Date: 2025-08-20 08:28:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('food_budget_type', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('food_budget_percentage', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('food_budget_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'food_budget_amount')
    op.drop_column('user', 'food_budget_percentage')
    op.drop_column('user', 'food_budget_type')
    # ### end Alembic commands ###
